In [1]:
import argparse
import json
import os
import pathlib
import sys
import time

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import psutil
import scipy
import tifffile
import torch
from arg_parsing_utils import check_for_missing_args, parse_args
from cellpose import models
from file_reading import *
from file_reading import read_zstack_image
from general_segmentation_utils import *
from notebook_init_utils import bandicoot_check, init_notebook
from organoid_segmentation import *
from segmentation_decoupling import *
from skimage.filters import sobel
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
def read_labels(infile: str) -> dict:
    """
    Description
    ----------
    Read labels from a parquet file.
    Parameters
    ----------
    infile : str
        Path to the input parquet file.
    Returns
    -------
    dict
        Dictionary containing the labels.
    """
    data = pd.read_parquet(infile).to_dict(orient="list")
    return data

In [3]:
start_time = time.time()
# get starting memory (cpu)
start_mem = psutil.Process(os.getpid()).memory_info().rss / 1024**2

In [4]:
root_dir, in_notebook = init_notebook()

image_base_dir = bandicoot_check(
    pathlib.Path(os.path.expanduser("~/mnt/bandicoot")).resolve(), root_dir
)
patient_list_file_path = pathlib.Path(f"{root_dir}/data/patient_IDs.txt").resolve(
    strict=True
)

In [5]:
labels_save_file = pathlib.Path(
    "../image_labels/organoid_image_labels.parquet"
).resolve()
sammed_features_save_path = pathlib.Path(
    f"../../3.cellprofiling/results/sammed_features.parquet"
).resolve()
labels = read_labels(labels_save_file)
labels_df = pd.DataFrame(labels)
labels_df
sammed_features_df = pd.read_parquet(sammed_features_save_path)
sammed_features_df
df = pd.merge(
    sammed_features_df,
    labels_df,
    on=["patient", "well_fov"],
    how="right",
)
# drop rows with na
df = df.dropna(subset=["label"])
df

patient well_fov  405_SAMMed3D_feature_0  405_SAMMed3D_feature_1  \
0    NF0014_T1    C10-1               -0.319416               -0.301876   
1    NF0014_T1    C10-2               -0.262450               -0.291977   
2    NF0014_T1    C11-1               -0.245149               -0.331004   
3    NF0014_T1    C11-2               -0.252592               -0.328891   
4    NF0014_T1     C2-1               -0.213654               -0.348314   
..         ...      ...                     ...                     ...   
143  NF0014_T2     C5-6               -0.294294               -0.331082   
144  NF0014_T2     C5-7               -0.402969               -0.368304   
145  NF0014_T2     C6-1               -0.320862               -0.333989   
146  NF0014_T2     C6-2               -0.307637               -0.332819   
147  NF0014_T2     C6-3               -0.200959               -0.300805   

     405_SAMMed3D_feature_10  405_SAMMed3D_feature_100  \
0                   0.236247                 -0.006220   
1                   0.253318                  0.016509   
2                   0.227504                 -0.010081   
3                   0.218564                 -0.032857   
4                   0.227645                 -0.011737   
..                       ...                       ...   
143                 0.218519                 -0.010784   
144                 0.220878                  0.007899   
145                 0.223607                 -0.003560   
146                 0.221561                 -0.013901   
147                 0.186923                 -0.032969   

     405_SAMMed3D_feature_101  405_SAMMed3D_feature_102  \
0                   -0.155010                  0.167629   
1                   -0.097607                  0.184147   
2                   -0.153452                  0.186263   
3                   -0.171053                  0.201910   
4                   -0.186671                  0.208217   
..                        ...                       ...   
143                 -0.177558                  0.190228   
144                 -0.157321                  0.125653   
145                 -0.157684                  0.186301   
146                 -0.164055                  0.187039   
147                 -0.149016                  0.229566   

     405_SAMMed3D_feature_103  405_SAMMed3D_feature_104  ...  \
0                    0.024517                 -0.111055  ...   
1                    0.029037                 -0.125325  ...   
2                    0.018825                 -0.117956  ...   
3                    0.015939                 -0.130160  ...   
4                   -0.001262                 -0.114908  ...   
..                        ...                       ...  ...   
143                  0.018600                 -0.123144  ...   
144                  0.031363                 -0.081504  ...   
145                  0.017634                 -0.113109  ...   
146                  0.018587                 -0.103550  ...   
147                 -0.005350                 -0.127442  ...   

     TRANS_SAMMed3D_feature_92  TRANS_SAMMed3D_feature_93  \
0                    -0.122748                  -0.011013   
1                    -0.107115                  -0.011186   
2                    -0.122888                  -0.011035   
3                    -0.123045                  -0.011132   
4                    -0.140545                  -0.011159   
..                         ...                        ...   
143                  -0.097683                  -0.011064   
144                  -0.111580                  -0.011178   
145                  -0.107170                  -0.011085   
146                  -0.108075                  -0.011085   
147                  -0.095951                  -0.011042   

     TRANS_SAMMed3D_feature_94  TRANS_SAMMed3D_feature_95  \
0                     0.003297                  -0.104058   
1                     0.009765                  -0.084305   
2              

In [8]:
# set up data splits
# train: 70%, val: 15%, test: 15%
# stratify by label, patient

train_df, test_df = train_test_split(
    df,
    test_size=0.15,
    random_state=42,
    stratify=df[["label"]],
)
train_df, val_df = train_test_split(
    train_df,
    test_size=0.1765,  # 0.1765 * 0.85 = 0.15
    random_state=42,
    stratify=train_df[["label"]],
)
print(f"Train size: {len(train_df)}")
print(f"Validation size: {len(val_df)}")
print(f"Test size: {len(test_df)}")

Train size: 102
Validation size: 22
Test size: 22


In [9]:
# train a random forest classifier for the organoid labels


rf_model = RandomForestClassifier(n_estimators=1000, random_state=42)
rf_model.fit(
    train_df.drop(columns=["patient", "well_fov", "label", "annotator"]),
    train_df["label"],
)
val_preds = rf_model.predict(
    val_df.drop(columns=["patient", "well_fov", "label", "annotator"])
)
print("Validation Classification Report:")
print(classification_report(val_df["label"], val_preds))
print("Validation Confusion Matrix:")
print(confusion_matrix(val_df["label"], val_preds))
test_preds = rf_model.predict(
    test_df.drop(columns=["patient", "well_fov", "label", "annotator"])
)
print("Test Classification Report:")
print(classification_report(test_df["label"], test_preds))
print("Test Confusion Matrix:")
print(confusion_matrix(test_df["label"], test_preds))

Validation Classification Report:
              precision    recall  f1-score   support

 dissociated       0.67      0.25      0.36         8
   elongated       0.00      0.00      0.00         1
    globular       0.60      0.86      0.71         7
       small       0.56      0.83      0.67         6

    accuracy                           0.59        22
   macro avg       0.46      0.49      0.43        22
weighted avg       0.58      0.59      0.54        22

Validation Confusion Matrix:
[[2 0 3 3]
 [0 0 0 1]
 [1 0 6 0]
 [0 0 1 5]]
Test Classification Report:
              precision    recall  f1-score   support

 dissociated       0.00      0.00      0.00         8
   elongated       0.00      0.00      0.00         2
    globular       0.70      1.00      0.82         7
       small       0.45      1.00      0.62         5

    accuracy                           0.55        22
   macro avg       0.29      0.50      0.36        22
weighted avg       0.33      0.55      0.40      

/home/lippincm/miniforge3/envs/GFF_segmentation_nuclei/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/lippincm/miniforge3/envs/GFF_segmentation_nuclei/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/lippincm/miniforge3/envs/GFF_segmentation_nuclei/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to contr